/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    // 4つのパターンを順番に呼び出す
    printResult(5, 2); // T, F
    printResult(16, 4); // F, F
    printResult(9, 20); // T, T
    printResult(30, 10); // F, T
  }

  // 出力のための補助メソッド
  public static void printResult(int age, int size) {
    Calculate calc = new Calculate();
    int individual = calc.getIndividualFee(age);
    int total = calc.getTotalFee(age, size);
    if (size >= 10) {
      System.out.println("Age " + age + ", Size " + size + ": Individual " + individual + ", Total " + total
          + " (Discount applied).");
    } else {
      System.out.println("Age " + age + ", Size " + size + ": Individual " + individual + ", Total " + total + ".");
    }
  }
}
